version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql  #ローカルのディレクトリ:dockerのディレクトリに同期する
    environment:
      MYSQL_ROOT_PASSWORD: password   #環境変数の設定
  web:
    build: .  #同じディレクトリのdockerfileを使う（.）
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    depends_on:
      - db